[package]
name = "totp_rfc6238"
version = "0.4.0"
authors = ["KaneGreen <737445366KG@Gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/KaneGreen/totp_rfc6238"
documentation = "https://docs.rs/totp_rfc6238"
keywords = ["authentication", "hmac", "otp", "totp", "2fa"]
categories = ["authentication", "web-programming"]
description = "library for generating TOTP codes (tokens) defined in RFC 6238"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = [ "oathuri" ]

[features]
default = []
oathuri = [ "data-encoding", "percent-encoding", "url", "zeroize" ]

[dependencies]
ring = '^0.16.20'
data-encoding = { version = "^2.3.2", optional = true }
percent-encoding = { version = "^2.1.0", optional = true }
url = { version = "^2.2.2", optional = true }
zeroize = { version = "^1.3.0", optional = true }
