name: Rust-test

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/rust-test.yml'
      - 'src/**'
      - 'Cargo.toml'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/rust-test.yml'
      - 'src/**'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: |
        rustup self update
        rustup default stable
        rustup update --no-self-update
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
