name: Rust-test

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/rust-test.yml'
      - 'src/**'
      - 'Cargo.toml'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/rust-test.yml'
      - 'src/**'
      - 'Cargo.toml'

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: x86_64-pc-windows-msvc
          os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Update Rust
      run: |
        rustup self update
        rustup default stable-${{ matrix.target }}
        rustup update --no-self-update

    - name: Build
      run: |
        cargo build --verbose --features oathuri
        cargo clean
        cargo build --verbose --no-default-features --features ring --features oathuri

    - name: Run tests
      run: |
        cargo test --verbose --features oathuri
        cargo clean
        cargo test --verbose --no-default-features --features ring --features oathuri
